### PR TITLE
Add config option to specify the path to place the generated nginx configuration file

### PR DESCRIPTION
**Pull request by samdjstevens**
Hi,

Great plugin - solves the exact problem I am currently facing at work. One initial problem I had using it was that when installing NGINX on my host laptop (macOS) via Homebrew, the default install path was `/usr/local/etc/nginx`, and not `/etc/nginx`.

This PR adds an optional configuration option to specify this path, defaulting to the current `/etc/nginx`.

I'm not a Ruby dev but hopefully everything is okay with the code...

### CODE REVIEW

**Comment by sjamaan** [comment]
Hi! Thanks for the pull request. Having a hardcoded config path is definitely an oversight that needs to be fixed.

I'll probably be able to test this properly next week. From a first glance over the code, it looks good to me. I have a few comments and suggestions so far:
- Instead of an `if` block, it'd be less "noisy" if you used `nginx_dir = @config.reverse_proxy.nginx_dir || '/etc/nginx'` (this is just a matter of taste though).
- Could you please add a description of this new configuration option to the README?
- Maybe instead of using a hardcoded filename under a configurable prefix, it would be a bit more flexible if the target file itself could be configured. The `nginx_dir` can be derived from it using `File.dirname(foo)`. What do you think?

**Comment by samdjstevens** [comment]
Agree with all the points - I've pushed a commit up that hopefully deals with  them all!

**Comment by sjamaan** [comment]
I just tested it and took a closer look at the code, and I noticed two things:

- `@config` is not set in this method in my version of Vagrant, resulting in a crash.  This should be `env[:machine].config`, like in the `enabled?` check in the line above it.
- `nginx_site` is a bit of a strange name for this variable; it's not a site, but a configuration file with several proxy settings.  How about `nginx_file` or `config_file`? If the latter, I would recommend changing `nginx_dir` to `config_dir`, to match it.

If you can change these two things I can accept the pull request.

**Comment by samdjstevens** [comment]
Ah yes sorry i was testing my additions on the latest release tag (with @config) but applying the changes on master. I've fixed that now and made the variable name changes.

**Comment by sjamaan** [comment]
Cool, thanks!

**Pull request merged**
